sudo: required
dist: trusty
language: python
cache:
  - pip
  - apt

python:
  - 2.7
  - 3.6

before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get update
  - sudo apt-get install -y geoipupdate
  - echo 'UserId 999999' | sudo tee /etc/GeoIP.conf > /dev/null
  - echo 'LicenseKey 000000000000' | sudo tee -a /etc/GeoIP.conf > /dev/null
  - echo 'ProductIds GeoLite2-Country GeoLite2-City GeoLite2-ASN' | sudo tee -a /etc/GeoIP.conf > /dev/null
  - sudo geoipupdate -v

install:
  - pip install -r dev_requirements.txt

script:
  - python setup.py test
  - python setup.py sdist bdist bdist_wheel

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: M77GYpseC/BRIUUT1ZUTVAAwkUxbckn/sZI8fX4vUPXCcVOMWC1I5ussjrN9ADq/+EQ/+Wh0cJvLbF75oo5uNUHth7HoaSHDeBhcLajcLo2Bnl/F4AnM3+ZZnJROxQMm/2/Tv7+1/FM9Ez/DJ220f3l6FqqDoT3CJGVs0KwGk66rTWNFyuF6yPm6rlAnwyzwJOI8B6NLybbLHCrmNxSvH5I5hYpc6Hw8gGk1bNBzQdplWCNt8AVL+L8m9ngPHPeqXRvQQV0XQGWBTvUmcosf3KgNMqYSP7TIJ/O0YktpuZY0YYlvxeDOtuosoH4r3DjanHNRVM8CjfobpmgrpYPwmVWiNB0LA63acips8jBkC/I89vuFBKNcEi2aVXMlvmPezbYKDEUnWeB8rG6tKbQwOH8g9q+JbIpDBkG0GlgwFGAyKi+dfSjjhSTaXXthWGaZtmLDydwzxvOBJM2br6Sd5ivmD2ppmzREDRC0yqeyfz6TclbQw6Jy0Av0T99I9gMOxMelmXhpk80sK2JLgg641hiYEMc4ueQNlPL2ZzVInrfrS5UeUITE6SjvhNbvmxTX4nmToAX5jJZtn2gwcpo3F190XsYSl1FeZ7NQ+NuLJeKjYnnp8pUNqIV71reQIslow4dghwMQi+a5eiqOysP/sgW0HgIq5+T6L/8BC9L1Ras=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
